name: advent-haskell
version: 0.1.0.0
github: neillrobson/advent-haskell
author: Neill Robson
maintainer: neill@neillrobson.com
license: BSD-3-Clause
copyright: 2025 - Present
extra-source-files:
  - README.md
  - CHANGELOG.md

description: Please see the README on GitHub at
  <https://github.com/neillrobson/advent-haskell#readme>

spec-version: 0.39.1

dependencies:
  - advent-of-code-api
  - aeson
  - base >=4.7 && <5
  - bytestring
  - containers
  - deepseq
  - text
  - template-haskell
  - yaml

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - TemplateHaskell
  - ViewPatterns

executables:
  advent-haskell:
    source-dirs: src
    main: Main.hs
